auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: nongdabang.com
url: http://nongdabang.com
feed: /atom.xml
author_info: <a href="http://nongdabang.com/">TongChen</a>
